


// ALl the sender ids of all major and some co operative banks
class BankData{
static  bool IsStrictlyATransaction(String senderid){
    if(senderid.contains("-")){
      if(bankids.contains(senderid.split("-")[1])){
        return true;
      }
    }
    return false;
  }
  static List<String> bankids=[
    "ACBLBK",
    "ADARSH",
    "ADHBNK",
    "ADRBNK",
    "AMCBNK",
    "AMCOBK",
    "AIRBNK",
    "AIRBSE",
    "AIRBSI",
    "ALBANK",
    "ANDBNK",
    "APGVBK",
    "APSCOB",
    "HORRMD",
    "ROATPM",
    "ROKDPA",
    "ROKDRI",
    "ROKRNL",
    "RONDYL",
    "RONELR",
    "ROONGL",
    "RORJPA",
    "APGBBK",
    "APGBHO",
    "APGBIT",
    "APGBNK",
    "APGECM",
    "APHOAT",
    "APNABK",
    "APNAPR",
    "APNATR",
    "AUBANK",
    "AUBMSG",
    "AUBSMS",
    "AUDOST",
    "AUITSM",
    "AXISB",
    "AXISBK",
    "AXISHR",
    "AXISIN",
    "AXISMR",
    "AXISPR",
    "AXISSR",
    "AXSFI",
    "AXSFIN",
    "FCHRGE",
    "LICCRD",
    "SMGPAY",
    "BKBANK",
    "BNDNBK",
    "BNDNHL",
    "BDNSMS",
    "BOBBIZ",
    "BOBBNK",
    "BOBCMS",
    "BOBCRM",
    "BOBFRM",
    "BOBMSG",
    "BOBOTP",
    "BOBRAJ",
    "BOBSCE",
    "BOBSCF",
    "BOBSMS",
    "BOBTRE",
    "BOBTXN",
    "BOBUPG",
    "BOBUPI",
    "BOIBAL",
    "BOIIND",
    "BOIINT",
    "BOIJGB",
    "BOILON",
    "BOINJG",
    "BOIREM",
    "BOISAF",
    "BOISME",
    "BOIVKG",
    "BOMSCT",
    "MAHABK",
    "DPCSDX",
    "EBTALT",
    "HDFCAL",
    "HDFCBA",
    "HDFCBK",
    "HDFCBN",
    "HDFCCC",
    "HDFCDC",
    "HDFCFD",
    "HDFCGC",
    "HDFCHI",
    "HDFCHL",
    "HDFCLI",
    "HDFCPL",
    "HDFCRD",
    "HDFCSD",
    "HDFCSE",
    "HDFCUN",
    "HDFSET",
    "HDFTST",
    "HDFCIT",
    "MIMTMX",
    "PAYZAP",
    "UNIXCE",
    "EBTALT",
    "ICBANK",
    "ICIBNK",
    "ICICBK",
    "ICICIB",
    "ICICIH",
    "ICICIK",
    "ICICIL",
    "ICICTC",
    "ICIEMP",
    "ICIOTP",
    "ISECLD",
    "ISRVCE",
    "PNBCCD",
    "PNBCRD",
    "PNBCRM",
    "PNBDBD",
    "PNBHRD",
    "PNBJNK",
    "PNBLKO",
    "PNBMKT",
    "PNBOTP",
    "PNBRTS",
    "PNBSMS",
    "PNBTBD",
    "KTKREM",
    "KOTAKP",
    "KOTAKB",
    "KBANKT",
    "LCTSCS",
    "LHOABU",
    "LHOBAN",
    "LHOGMI",
    "LHOKOL",
    "LHOPAT",
    "MABHYD",
    "MISDEP",
    "PIMSBI",
    "PPGDEP",
    "PVIJAY",
    "RBOPEN",
    "RMMBNR",
    "RMRBLY",
    "SAMLMS",
    "SBBJNB",
    "SBCDRE",
    "SBCWMS",
    "SBDBTL",
    "SBDCOG",
    "SBECOM",
    "SBEPAY",
    "SBEREG",
    "SBERMS",
    "SBFIAH",
    "SBFIMF",
    "SBGALR",
    "SBGITC",
    "SBGLMS",
    "SBGMBS",
    "SBGPPC",
    "SBHIGH",
    "SBHINB",
    "SBHRMS",
    "SBIABD",
    "SBIABU",
    "SBIACS",
    "SBIADS",
    "SBIAHM",
    "SBIAND",
    "SBIAOR",
    "SBIAPP",
    "SBIATM",
    "SBIATT",
    "SBIAVS",
    "SBIBAN",
    "SBIBHO",
    "SBIBHU",
    "SBIBNK",
    "SBIBOG",
    "SBIBSC",
    "SBIBTU",
    "SBICAA",
    "SBICAR",
    "SBICBG",
    "SBICDC",
    "SBICDS",
    "SBICHA",
    "SBICHD",
    "SBICHE",
    "SBICMD",
    "SBICMP",
    "SBICMS",
    "SBICON",
    "SBICOS",
    "SBICPA",
    "SBICPC",
    "SBICPP",
    "SBICRS",
    "SBICVC",
    "SBICVE",
    "SBICVS",
    "SBICWS",
    "SBIDAK",
    "SBIDBT",
    "SBIDCL",
    "SBIDEL",
    "SBIDGT",
    "SBIDIA",
    "SBIDMO",
    "SBIDMT",
    "SBIDRC",
    "SBIDRT",
    "SBIDSB",
    "SBIDTB",
    "SBIDYN",
    "SBIEES",
    "SBIEIS",
    "SBIEMM",
    "SBIEST",
    "SBIETC",
    "SBIETF",
    "SBIETM",
    "SBIEWS",
    "SBIFIJ",
    "SBIFMC",
    "SBIFMS",
    "SBIFOB",
    "SBIFRW",
    "SBIFXT",
    "SBIGAD",
    "SBIGCC",
    "SBIGKP",
    "SBIGLM",
    "SBIGLS",
    "SBIGMU",
    "SBIGOC",
    "SBIGRC",
    "SBIGUW",
    "SBIHOM",
    "SBIHRD",
    "SBIHSG",
    "SBIHUB",
    "SBIHYD",
    "SBIINB",
    "SBIINF",
    "SBIITS",
    "SBIIVM",
    "SBIJAI",
    "SBIKBN",
    "SBIKBP",
    "SBIKER",
    "SBIKOL",
    "SBIKYC",
    "SBILCM",
    "SBILCO",
    "SBILKL",
    "SBILON"  ,
    "SBILOS"   ,
    "SBILOT"    ,
    "SBILTP"     ,
    "SBILUC"     ,
    "SBILWF"     ,
    "SBIMAB"      ,
    "SBIMAH"      ,
    "SBIMAP"      ,
    "SBIMAT"      ,
    "SBIMBD"      ,
    "SBIMBS"     ,
    "SBIMET"     ,
    "SBIMFK"     ,
    "SBIMUM"      ,
    "SBINPA"     ,
    "SBINPS"     ,
    "SBINTH"     ,
    "SBINWC"      ,
    "SBINWD"      ,
    "SBINZB"     ,
    "SBIOEM"      ,
    "SBIONB"     ,
    "SBIOTP"     ,
    "SBIOTS"     ,
    "SBIPAY"     ,
    "SBIPBS"     ,
    "SBIPBU"     ,
    "SBIPEN"     ,
    "SBIPER"     ,
    "SBIPNJ"     ,
    "SBIPOS"     ,
    "SBIPPC"     ,
    "SBIPRM"      ,
    "SBIPSG"     ,
    "SBIPSP"     ,
    "SBIQCK"     ,
    "SBIRBH"     ,
    "SBIRBU"     ,
    "SBIRCH"     ,
    "SBIRDH"     ,
    "SBIREG"     ,
    "SBIREH"     ,
    "SBIRMD"     ,
    "SBIRPR"     ,
    "SBIRTI"    ,
    "SBIRWZ"     ,
    "SBISAM"     ,
    "SBISBD"     ,
    "SBISEC"    ,
    "SBISFG"    ,
    "SBISMA"     ,
    "SBISMB"     ,
    "SBISMC"     ,
    "SBISME"     ,
    "SBISMP"     ,
    "SBISNB"     ,
    "SBISNC"     ,
    "SBISNP"     ,
    "SBISOC"     ,
    "SBISOM"     ,
    "SBISRP"    ,
    "SBITBU"     ,
    "SBITDS"    ,
    "SBITFF"  ,
    "SBITFO"  ,
    "SBITRB"   ,
    "SBITRI"  ,
    "SBITRN"   ,
    "SBITRS"  ,
    "SBITSM"  ,
    "SBITSS",
    "SBITST",
    "SBIUDR" ,
    "SBIUPI"   ,
    "SBIVMT"   ,
    "SBIVPN"  ,
    "SBIWAL"   ,
    "SBIWEB"    ,
    "SBJSMS"   ,
    "SBLCPC"  ,
    "SBLLMS" ,
    "SBLSOL"  ,
    "SBLSPC" ,
    "SBMBNK" ,
    "SBMCB"  ,
    "SBMCBK" ,
    "SBMCSH"   ,
    "SBMINB"  ,
    "SBMIND" ,
    "SBOCAS"  ,
    "SBPBBU" ,
    "SBPINB",
    "SBRACC",
    "SBRLMS"  ,
    "SBRWDZ"   ,
    "SBSSBI" ,
    "SBTINB"  ,
    "SBWLTH"   ,
    "SBYONO"   ,
    "WMBSMS"  ,
    "SSKSBH"  ,
    "SSKSBI"  ,
    "SSKSBM"  ,
    "SSKSBP" ,
    "SSKSBT",
    "SSCORE",
    "SBWLTH",
    "SOCINC",
    "SBYONO",
    "SBTINB",
    "SBSSBI",
    "SBLCPC",
    "SBLLMS",
    "SBLSOL",
    "SBLSPC",
    "SBMBNK",
    "SBMCB",
    "SBMCBK",
    "SBMCSH",
    "SBMINB",
    "SBMIND",
    "SBOCAS",
    "SBPBBU",
    "SBPINB",
    "SBRACC",
    "SBRLMS",
    "SBRWDZ",
    "SBSSBI",
    "SBTABK",
    "SBTINB",
    "CAANBK",
    "CANBNK",
    "CANRRB",
    "CANRWD",
    "UNIONB",
    "INBUPI",
    "INDBNK",
    "SIBCNP",
    "SIBPRD",
    "SIBSMS",
    "CBIOTP",
    "CENTBK",
    "IOBANK",
    "IOBATM",
    "IOBBNK",
    "IOBBQR",
    "IOBCHN",
    "IOBHRD",
    "IOBJLS",
    "IOBMKT",
    "IOBOTP",
    "UCOBNK",
    "PSBANK",
    "CUBANK",
    "CUBFST",
    "CUBLTD",
    "CUBOTP",
    "CUBSMS",
    "CUBUPI",
    "YESBCC"    ,
    "YESBCM"   ,
    "YESBNK"    ,
    "YESPAY"    ,

    "VIKASB"    ,
    "VVSBNK"    ,
    "VARABK"    ,
    "UGBBNK"   ,
    "AGVBNK"    ,
    "AGVCBS"    ,
    "BGVBNK"    ,
    "BGVCBS"    ,
    "MRBANK"    ,
    "MRBCBS"    ,
    "TGBANK"    ,
    "TGBCBS"   ,
    "UBIBNK"   ,
    "UBISMS"    ,

    "UNIONB"    ,

    "UJJIVN"   ,
    "UJVNBP"   ,
    "UCOBNK"   ,

    "VCBANK"    ,
    "VIJBNK"    ,
    "TUCBLD"    ,
    "URBANK"    ,
    "UUCBUD"    ,
    "UMSBNK"    ,
    "UMUCBK"    ,
    "UMUCBL"    ,
    "SDCCBK"    ,

    "TMBANK"     ,
    "TMBFST"     ,
    "TMBOTP"     ,
    "TMBSMS"     ,
    "TMBUPI"     ,
    "RBLBBB"   ,
    "RBLBNK"    ,
    "RBLCCC"    ,
    "RBLCRD"    ,
    "RBLINF"    ,
    "RBLKYC"    ,
    "RBLOFR"    ,
    "RBLOSR"    ,
    "RBLPIL"    ,
    "RBLPLN"    ,
    "RBLSLE"    ,
    "RBLSSU"    ,
    "RBLTEC"    ,
    "RBLVPN"     ,
    "RBLWCM"     ,
    "SPRCRD"     ,
    "SPROFR"     ,
    "TNBLTD"   ,
    "NTLBNK"    ,
    "LVBANK"    ,
    "LVBSMS"    ,
    "KBANKT"     ,
    "KOTAKB"   ,
    "KOTAKP"    ,
    "KTKBNK"    ,
    "KARBNK"    ,
    "KBLBNK"     ,
    "KRNBNK"     ,
    "KRTBNK"    ,
    "JKBANK"     ,
    "JKCARD"     ,
    "INDUSA"     ,
    "INDUSB"     ,
    "INDUSO"     ,
    "IDFCBK"     ,
    "IDFCCM"      ,
    "IDFCFB"    ,
    "IDFCFZ"    ,
    "IDFCIT"   ,
    "IDFCTS"     ,
    "IDFCZ"   ,
    "IDFSIT"   ,
    "IDBIBK"    ,
    "IDBIDL"   ,
    "ISECLD"    ,
    "ISRVCE"    ,
    "ICBANK"    ,
    "ICIBNK"    ,
    "ICICBK"    ,
    "ICICIB"  ,
    "ICICIH"   ,
    "ICICIK"  ,
    "ICICIL"   ,
    "ICICIP"   ,
    "ICICTC"    ,
    "ICIEMP"     ,
    "ICIOTP"    ,
    "MIMTMX"    ,
    "PAYZAP"    ,
    "UNIXCE"   ,
    "DPCSDX"   ,
    "EBTALT"   ,
    "HDFCAL"    ,
    "HDFCAR"   ,
    "HDFCBA"   ,
    "HDFCBF"    ,
    "HDFCBK"    ,
    "HDFCBN"    ,
    "HDFCCC"   ,
    "HDFCCI"    ,
    "HDFCDC"    ,
    "HDFCFD"   ,
    'HDFCGC'    ,
    "HDFCGI"    ,
    "HDFCHI"    ,
    "HDFCHL"    ,
    "HDFCIN"    ,
    "HDFCIT"   ,
    "HDFCLD"    ,
    "HDFCLI"   ,
    "HDFCMF"    ,
    "HDFCPD"   ,
    "HDFCPL"    ,
    "HDFCPN"   ,
    "HDFCRD"    ,
    "HDFCSC"   ,
    "HDFCSD"   ,
    "HDFCSE"   ,
    "HDFCSL"    ,
    "HDFCUN"   ,
    "HDFSET"    ,
    "HDFTST"   ,
    "HRHDFC"   ,
    "FEDADV"    ,
    "FEDBNK"  ,
    "FEDOTP"    ,
  ];
}
